CREATE TABLE [Users] (
    Id INT IDENTITY PRIMARY KEY,
    SpotifyId NVARCHAR(100) UNIQUE,
	Username NVARCHAR(50) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
    DisplayName NVARCHAR(100),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    ProfileImage NVARCHAR(500),
    CreatedAt DATETIME DEFAULT GETDATE()
);