CREATE TABLE Follows (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FollowerId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
  FollowingId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
  CreatedAt DATETIME DEFAULT GETDATE(),
  UNIQUE (FollowerId, FollowingId)
);
