CREATE TABLE Reviews (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
  SpotifyItemId NVARCHAR(100) NOT NULL,   -- NO FOREIGN KEY
  Rating INT CHECK (Rating BETWEEN 1 AND 5),
  ReviewText NVARCHAR(MAX),
  Likes INT DEFAULT 0,
  CreatedAt DATETIME DEFAULT GETDATE()
);